name: learn-github-action
on: [push] # event to run the workflow
jobs: # collection of jobs to run
    # job name
    check-bats-version:
        runs-on: ubuntu-latest # specify virtual machine to run on
        steps:
            - uses: actions/checkout@v2 #  tells the job to retrieve v2 of the community action named actions/checkout@v2.
            - uses: actions/setup-node@v1 # tells the jobs to setup npm
            - run: npm install -g bats
            - run: bats -v


