name: learn-github-action
on: [push] # event to run the workflow
jobs: # collection of jobs to run
    # job name
    build:
        runs-on: ubuntu-latest # specify virtual machine to run on
        steps:
            - uses: actions/checkout@v2 #  tells the job to retrieve v2 of the community action named actions/checkout@v2.

            - uses: lukka/get-cmake@v3.19.2 # tells the jobs to setup cmake

            - run: mkdir externs

            - name: cache doctest
              uses: actions/cache@v2
              id: cache-doctest
              env:
                cache-name: cache-doctest-2.4.5
              with:
                path: ~/externs/doctest-install
                key: ${{runner.os}}-build-${{env.cache-name}}

            - name: build and install doctest
              working-directory: externs
              if: steps.cache-doctest.outputs.cache-hit != 'true'
              run: |
                git clone --depth 1 --branch 2.4.5 https://github.com/onqtam/doctest.git
                mkdir doctest-build && cd doctest-build
                cmake ../doctest -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/externs/doctest-install"
                make install

            - name: cache benchmark
              uses: actions/cache@v2
              id: cache-benchmark
              env:
                cache-name: cache-benchmark-v1.5.2
              with:
                path: ~/externs/benchmark-install
                key: ${{runner.os}}-build-${{env.cache-name}}

            - name: build and install benchmark
              working-directory: externs
              if: steps.cache-benchmark.outputs.cache-hit != 'true'
              run: |
                git clone --depth 1 --branch v1.5.2 https://github.com/google/benchmark.git
                mkdir benchmark-build && cd benchmark-build
                cmake ../benchmark -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_TESTING=OFF -DCMAKE_INSTALL_PREFIX="~/externs/benchmark-install"
                make install

            - name: build
              run: |
                mkdir build && cd build
                cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="~/externs"
                make

            - name: test
              working-directory: build
              run: |
                ./test/test


